<script lang="ts">
  import { isExecutableAgent } from "./types.js";
  import {
    applySplitProposal,
    createTask,
    suggestSplit,
    type CreatedTask,
    type ProposedTask,
  } from "./api.js";
  import { focusTrap } from "./DialogShell.svelte";
  import { formatAgentLabel } from "./agent-label.js";
  import { t } from "./i18n.svelte.js";
  import { getShowReviewColumn } from "./settings.svelte.js";
  import type { AgentSummary } from "./types.js";

  interface Props {
    availableRepos: string[];
    agents?: AgentSummary[];
    agentId?: string | null;
    hasGitRepository?: boolean;
    onClose: () => void;
    onCreated?: (result: { taskId: string; subTasksCreated: number }) => void;
  }

  let { availableRepos, agents = [], agentId = null, hasGitRepository = true, onClose, onCreated }: Props = $props();

  function focusOnMount(node: HTMLElement): void {
    queueMicrotask(() => node.focus());
  }

  const DEFAULT_PLANNER_PROMPT = "Split the task so the work can run in parallel with as few dependencies as possible. Group independent files into balanced batches according to max_subagents. Only add dependencies when one sub-task truly needs another sub-task's output.";

  type ClarificationPrompt = {
    id: string;
    question: string;
    promptQuestion: string;
    options: Array<{ label: string; value: string }>;
  };

  type Phase = "input" | "clarify" | "creating" | "splitting" | "proposal" | "applying" | "applied";

  let phase = $state<Phase>("input");
  // Title field removed — the server synthesises one from the
  // description via the AI title-suggester (verb-led imperative,
  // ≤70 chars). We display the resolved title back to the user
  // after creation in the applied phase.
  let description = $state("");
  let priority = $state<"P0" | "P1" | "P2" | "P3">("P2");
  // Filled after createTask() returns — used to show the resolved
  // title + a small "Generated by …" hint in the applied phase.
  let titleSource = $state<"user" | "ai" | "fallback" | null>(null);
  let titleModel = $state<string | null>(null);
  let repoTargets = $state<string[]>([]);
  let error = $state<string | null>(null);
  const showReview = $derived(getShowReviewColumn());

  // Execution defaults the user picks at task creation time. Inherited
  // by the sub-task auto-shim and (eventually) by AI-split sub-tasks.
  let manualApproval = $state(false);
  // Commit / push / PR / merge: the user's "what should happen at the
  // end of the run?" sequence. Defaults match the most common case —
  // commit + push on, PR + merge off (PR creation needs gh installed).
  let commitWhenDone = $state(true);
  let pushWhenDone = $state(true);
  let createPr = $state(false);
  let mergePr = $state(false);
  // Where the agent works. "direct" lands the edits straight in the
  // user's working copy — what most users actually expect when they
  // click Play on a single quick task. "isolated_worktree" is for
  // multi-agent parallelism / longer runs where they want their main
  // branch protected.
  let worktreeMode = $state<"isolated_worktree" | "direct">("direct");

  $effect(() => {
    if (!showReview) manualApproval = false;
  });

  $effect(() => {
    if (!hasGitRepository) {
      worktreeMode = "direct";
      commitWhenDone = false;
      pushWhenDone = false;
      createPr = false;
      mergePr = false;
    }
  });

  $effect(() => {
    if (worktreeMode === "direct") {
      createPr = false;
      mergePr = false;
      if (!commitWhenDone) pushWhenDone = false;
    } else {
      commitWhenDone = true;
      if (!pushWhenDone) {
        createPr = false;
        mergePr = false;
      }
      if (!createPr) mergePr = false;
    }
  });

  // AI splitter. It is conditional ("only if needed"); most tasks run
  // directly as one unit. maxSubagents is both the planning cap and
  // the later launch cap for this task.
  let autoSplit = $state(false);
  let maxSubagents = $state(5);
  let subAgentId = $state<string | null>(null);
  let plannerPrompt = $state(DEFAULT_PLANNER_PROMPT);
  let clarificationPrompts = $state<ClarificationPrompt[]>([]);
  let clarificationAnswers = $state<Record<string, string>>({});

  let createdTask = $state<CreatedTask | null>(null);
  let proposalTasks = $state<ProposedTask[]>([]);
  let proposalRationale = $state("");
  let proposalModel = $state("");
  let aiUnavailable = $state(false);
  let aiUnavailableDetail = $state("");
  let createdNotificationSent = $state(false);

  const executableAgents = $derived(
    agents.filter((agent) =>
      isExecutableAgent(agent) &&
      !agent.needs_api_key,
    ),
  );
  const clarificationComplete = $derived(
    clarificationPrompts.every((prompt) => (clarificationAnswers[prompt.id] ?? "").trim().length > 0),
  );

  $effect(() => {
    if (subAgentId && executableAgents.some((agent) => agent.id === subAgentId)) return;
    subAgentId = agentId && executableAgents.some((agent) => agent.id === agentId)
      ? agentId
      : executableAgents[0]?.id ?? agentId ?? null;
  });

  $effect(() => {
    if (autoSplit && hasGitRepository) {
      worktreeMode = "isolated_worktree";
    }
  });

  function normalizedMaxSubagents(): number {
    return Math.max(1, Math.min(99, Math.round(Number(maxSubagents) || 5)));
  }

  function notifyCreated(subTasksCreated: number) {
    if (!createdTask || createdNotificationSent) return;
    createdNotificationSent = true;
    onCreated?.({ taskId: createdTask.id, subTasksCreated });
  }

  function closeDialog() {
    notifyCreated(0);
    onClose();
  }

  function toggleRepo(id: string) {
    repoTargets = repoTargets.includes(id) ? repoTargets.filter((r) => r !== id) : [...repoTargets, id];
  }

  function hasConcreteTarget(text: string): boolean {
    return /(?:^|\s)[\w .@()[\]-]+\.(?:html?|tsx?|jsx?|svelte|css|scss|json|ya?ml|md|txt|ts|js|rb|py|go|rs|swift|kt|java|php|sql)\b/i.test(text) ||
      /(?:^|\s)(?:src|app|packages|components|pages|routes|screens|lib|server|client|docs|tests?)\//i.test(text) ||
      /\b(?:header|sidebar|modal|dialog|dropdown|button|menu|api|endpoint|command|readme|hook|diff|board|task|run|workspace|repository|git)\b/i.test(text);
  }

  function buildClarificationPrompts(text: string): ClarificationPrompt[] {
    const lower = text.toLowerCase();
    const prompts: ClarificationPrompt[] = [];
    const words = lower.split(/\s+/).filter(Boolean);
    const vagueTarget = /\b(it|this|that|thing|stuff|bug|issue|screen|page|flow|ça|ceci|cela|truc|machin|bug|probl[eè]me|[ée]cran|page|flux)\b/i.test(text);
    const vagueAction = /\b(improve|make better|clean up|handle|manage|fix|change|update|am[ée]liore|am[ée]liorer|corrige|corriger|r[ée]pare|r[ée]parer|change|changer|g[eé]rer)\b/i.test(text);
    const repetitiveFiles = /\b(?:add|create|generate|cr[ée]e?r?|ajoute?r?|g[ée]n[èe]re?r?)\b[\s\S]*\b(?:\d+|ten|dix)\b[\s\S]*\b(?:files?|fichiers?)\b/i.test(text);
    const mentionsNaming = /\b(?:named?|names?|naming|appel|nomm|nom|index\d*|hello\d*|path|paths|chemin|pattern|convention)\b/i.test(text);

    if ((words.length <= 3 || (vagueAction && vagueTarget)) && !hasConcreteTarget(text)) {
      prompts.push({
        id: "target",
        question: t("create_task.clarify.question.target"),
        promptQuestion: "What is the exact scope?",
        options: [
          { label: t("create_task.clarify.option.current_workspace"), value: "Use the current workspace." },
          { label: t("create_task.clarify.option.visible_ui"), value: "Target the visible screen or component." },
          { label: t("create_task.clarify.option.specific_files"), value: "The exact files will be specified by the user." },
        ],
      });
    }

    if (vagueAction && /\b(improve|make better|clean up|am[ée]liore|am[ée]liorer|handle|manage|g[eé]rer)\b/i.test(text)) {
      prompts.push({
        id: "outcome",
        question: t("create_task.clarify.question.outcome"),
        promptQuestion: "What outcome is expected?",
        options: [
          { label: t("create_task.clarify.option.smallest_fix"), value: "Make the smallest safe fix that satisfies the request." },
          { label: t("create_task.clarify.option.ui_polish"), value: "Only improve visual polish; do not change behavior." },
          { label: t("create_task.clarify.option.refactor_only"), value: "Refactor without changing behavior." },
        ],
      });
    }

    if (repetitiveFiles && !mentionsNaming) {
      prompts.push({
        id: "naming",
        question: t("create_task.clarify.question.naming"),
        promptQuestion: "How should generated files be named?",
        options: [
          { label: t("create_task.clarify.option.index_files"), value: "Name the files index1.html, index2.html, and so on." },
          { label: t("create_task.clarify.option.hello_files"), value: "Name the files hello1.html, hello2.html, and so on." },
          { label: t("create_task.clarify.option.project_convention"), value: "Use the project's existing naming convention." },
        ],
      });
    }

    if (availableRepos.length > 1 && repoTargets.length === 0 && !availableRepos.some((repo) => lower.includes(repo.toLowerCase()))) {
      prompts.push({
        id: "workspace",
        question: t("create_task.clarify.question.workspace"),
        promptQuestion: "Which workspace should this target?",
        options: [
          { label: t("create_task.clarify.option.relevant_workspace"), value: "Use the most relevant workspace." },
          { label: t("create_task.clarify.option.all_workspaces"), value: "Use all workspaces if needed." },
          { label: t("create_task.clarify.option.choose_chips"), value: "Use the workspaces selected in the task form." },
        ],
      });
    }

    return prompts.slice(0, 3);
  }

  function setClarificationAnswer(id: string, value: string) {
    clarificationAnswers = { ...clarificationAnswers, [id]: value };
  }

  function descriptionWithClarifications(): string {
    const base = description.trim();
    const answered = clarificationPrompts
      .map((prompt) => {
        const answer = (clarificationAnswers[prompt.id] ?? "").trim();
        return answer ? `- ${prompt.promptQuestion} ${answer}` : "";
      })
      .filter(Boolean);
    if (answered.length === 0) return base;
    return `${base}\n\nClarifications:\n${answered.join("\n")}`;
  }

  async function createFromCurrentInput() {
    error = null;
    aiUnavailable = false;
    aiUnavailableDetail = "";
    phase = "creating";
    try {
      const taskDescription = descriptionWithClarifications();
      const input: Parameters<typeof createTask>[0] = {
        description: taskDescription,
        priority,
        status: "ready",
      };
      if (repoTargets.length > 0) input.repo_targets = repoTargets;
      input.manual_approval_required = showReview ? manualApproval : false;
      input.auto_commit = hasGitRepository ? (worktreeMode === "isolated_worktree" ? true : commitWhenDone) : false;
      input.push_when_done = hasGitRepository ? (worktreeMode === "direct" ? commitWhenDone && pushWhenDone : pushWhenDone) : false;
      input.create_pr = hasGitRepository && worktreeMode === "isolated_worktree" ? createPr : false;
      input.merge_pr = hasGitRepository && worktreeMode === "isolated_worktree" ? mergePr : false;
      input.worktree_mode = hasGitRepository ? worktreeMode : "direct";
      input.max_subagents = normalizedMaxSubagents();
      if (agentId) input.planner_agent_id = agentId;
      // Simple tasks should follow the header model at launch time.
      // Split tasks keep the chosen sub-agent model because that is part
      // of the parallel execution plan.
      if (autoSplit && subAgentId) input.preferred_agents = [subAgentId];
      const result = await createTask(input);
      const task = result.task;
      createdTask = task;
      titleSource = result.title_source;
      titleModel = result.title_model ?? null;
      // Only kick the AI splitter when the user explicitly opts in.
      // Most tasks (one HTML file, one fix, one PR) shouldn't be split;
      // splitting is for genuinely parallel-able multi-repository work.
      if (autoSplit && (repoTargets.length > 0 || availableRepos.length > 0)) {
        phase = "splitting";
        const result = await suggestSplit(task.id, {
          max_subagents: normalizedMaxSubagents(),
          planner_prompt: plannerPrompt.trim(),
          ...(agentId ? { planner_agent_id: agentId } : {}),
        });
        if (result.ok) {
          proposalTasks = result.proposal.tasks.map((t) => ({ ...t }));
          proposalRationale = result.proposal.rationale;
          proposalModel = result.proposal.model;
          phase = "proposal";
        } else {
          aiUnavailable = true;
          aiUnavailableDetail = result.detail;
          phase = "applied";
        }
      } else {
        // Skip the "applied" phase entirely. Setting `phase = "applied"`
        // briefly rendered "Tâche créée" / "✓ Tâche créée" before the
        // parent closes the dialog and surfaces one lightweight
        // confirmation toast. Starting is now an explicit Play action,
        // not a second modal immediately after creation.
        notifyCreated(0);
      }
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
      phase = "input";
    }
  }

  async function handleSubmit(event: SubmitEvent) {
    event.preventDefault();
    const prompts = buildClarificationPrompts(description.trim());
    if (prompts.length > 0) {
      clarificationPrompts = prompts;
      clarificationAnswers = {};
      phase = "clarify";
      return;
    }
    await createFromCurrentInput();
  }

  async function continueAfterClarification() {
    if (!clarificationComplete) return;
    await createFromCurrentInput();
  }

  async function applyProposal() {
    if (!createdTask) return;
    error = null;
    phase = "applying";
    try {
      const result = await applySplitProposal(createdTask.id, proposalTasks, false, normalizedMaxSubagents());
      const count = result.created_tasks.length;
      phase = "applied";
      notifyCreated(count);
    } catch (err) {
      error = err instanceof Error ? err.message : String(err);
      phase = "proposal";
    }
  }

  function skipSplit() {
    if (!createdTask) return;
    phase = "applied";
    notifyCreated(0);
  }

  function updateProposalTask(index: number, patch: Partial<ProposedTask>) {
    proposalTasks = proposalTasks.map((task, i) => (i === index ? { ...task, ...patch } : task));
  }

  function removeProposalTask(index: number) {
    proposalTasks = proposalTasks.filter((_, i) => i !== index);
  }
</script>

<div class="backdrop" onclick={closeDialog} role="presentation">
  <div use:focusTrap class="modal" onclick={(e) => e.stopPropagation()} role="dialog" aria-modal="true" tabindex={-1} onkeydown={(e) => { if (e.key === "Escape") closeDialog(); }}>
    <header>
      <h2>
        {#if phase === "input" || phase === "creating"}
          {t("create_task.title.input")}
        {:else if phase === "clarify"}
          {t("create_task.title.clarify")}
        {:else if phase === "splitting"}
          {t("create_task.title.splitting")}
        {:else if phase === "proposal"}
          {t("create_task.title.proposal")}
        {:else if phase === "applying"}
          {t("create_task.title.applying")}
        {:else}
          {t("create_task.title.applied")}
        {/if}
      </h2>
      <button type="button" class="close" onclick={closeDialog}>✕</button>
    </header>

    {#if error}
      <div class="error">{error}</div>
    {/if}

    {#if phase === "input" || phase === "creating"}
      <form class="body" onsubmit={handleSubmit}>
        <label>
          {t("create_task.field.description")}
          <textarea
            bind:value={description}
            rows="4"
            required
            use:focusOnMount
            placeholder={t("create_task.field.description_help")}
          ></textarea>
          <span class="field-hint">{t("create_task.field.description_title_hint")}</span>
        </label>

        <label>
          {t("create_task.field.priority")}
          <select bind:value={priority}>
            <option value="P0">{t("create_task.field.priority.p0")}</option>
            <option value="P1">{t("create_task.field.priority.p1")}</option>
            <option value="P2">{t("create_task.field.priority.p2")}</option>
            <option value="P3">{t("create_task.field.priority.p3")}</option>
          </select>
        </label>

        {#if availableRepos.length > 0}
          <div class="repos">
            <span class="label">{t("create_task.field.repos")}</span>
            {#each availableRepos as repo (repo)}
              <label class="chip">
                <input type="checkbox" checked={repoTargets.includes(repo)} onchange={() => toggleRepo(repo)} />
                {repo}
              </label>
            {/each}
          </div>
        {/if}

        {#if showReview}
          <fieldset class="execution">
            <legend>{t("create_task.execution.title")}</legend>
            <label class="toggle">
              <input type="checkbox" bind:checked={manualApproval} />
              <span>
                <span class="toggle-label">{t("create_task.execution.manual_approval")}</span>
                <span class="toggle-desc">{t("create_task.execution.manual_approval_desc")}</span>
              </span>
            </label>
          </fieldset>
        {/if}

        {#if hasGitRepository}
        <fieldset class="execution">
          <legend>{t("create_task.git.title")}</legend>

          <!-- Worktree mode first — it's the single biggest decision
               for this task: do you want the agent to touch your
               working copy directly, or do its thing in an isolated
               git worktree? Default is direct (matches the most
               common single-task expectation). -->
          <label class="select-row">
            <span class="select-label">{t("create_task.execution.worktree_mode")}</span>
            <select bind:value={worktreeMode}>
              <option value="direct">{t("create_task.execution.worktree_direct")}</option>
              <option value="isolated_worktree">{t("create_task.execution.worktree_isolated")}</option>
            </select>
            <span class="select-hint">
              {worktreeMode === "direct"
                ? t("create_task.execution.worktree_direct_hint")
                : t("create_task.execution.worktree_isolated_hint")}
            </span>
          </label>

          {#if worktreeMode === "direct"}
            <label class="toggle">
              <input type="checkbox" bind:checked={commitWhenDone} />
              <span>
                <span class="toggle-label">{t("create_task.execution.commit_when_done")}</span>
                <span class="toggle-desc">{t("create_task.execution.commit_when_done_desc")}</span>
              </span>
            </label>
            <label class="toggle">
              <input type="checkbox" bind:checked={pushWhenDone} disabled={!commitWhenDone} />
              <span>
                <span class="toggle-label">{t("create_task.execution.push_when_done")}</span>
                <span class="toggle-desc">{t("create_task.execution.push_when_done_desc")}</span>
              </span>
            </label>
          {:else}
            <label class="toggle">
              <input type="checkbox" bind:checked={pushWhenDone} />
              <span>
                <span class="toggle-label">{t("create_task.execution.push_when_done")}</span>
                <span class="toggle-desc">{t("create_task.execution.push_when_done_desc")}</span>
              </span>
            </label>
            <label class="toggle">
              <input type="checkbox" bind:checked={createPr} disabled={!pushWhenDone} />
              <span>
                <span class="toggle-label">{t("create_task.execution.create_pr")}</span>
                <span class="toggle-desc">{t("create_task.execution.create_pr_desc")}</span>
              </span>
            </label>
            <label class="toggle">
              <input type="checkbox" bind:checked={mergePr} disabled={!createPr} />
              <span>
                <span class="toggle-label">{t("create_task.execution.merge_pr")}</span>
                <span class="toggle-desc">{t("create_task.execution.merge_pr_desc")}</span>
              </span>
            </label>
          {/if}

        </fieldset>
        {/if}

        <fieldset class="execution">
          <legend>{t("create_task.ai.title")}</legend>
          <label class="toggle">
            <input type="checkbox" bind:checked={autoSplit} />
            <span>
              <span class="toggle-label">{t("create_task.ai.auto_split")}</span>
              <span class="toggle-desc">{t("create_task.ai.auto_split_desc")}</span>
            </span>
          </label>
          {#if autoSplit}
            <div class="ai-tuning">
              <label class="number-row">
                <span>{t("create_task.ai.max_subagents")}</span>
                <input type="number" min="1" max="99" bind:value={maxSubagents} />
              </label>
              {#if executableAgents.length > 0}
                <label class="select-row compact">
                  <span class="select-label">{t("create_task.ai.subagent_model")}</span>
                  <select bind:value={subAgentId}>
                    {#each executableAgents as agent (agent.id)}
                      <option value={agent.id}>{formatAgentLabel(agent).withContext}</option>
                    {/each}
                  </select>
                  <span class="select-hint">{t("create_task.ai.subagent_model_hint")}</span>
                </label>
              {/if}
              <label class="prompt-row">
                <span>{t("create_task.ai.planner_prompt")}</span>
                <textarea bind:value={plannerPrompt} rows="4"></textarea>
              </label>
            </div>
          {/if}
        </fieldset>

        <footer>
          <button type="button" onclick={closeDialog}>{t("create_task.button.cancel")}</button>
          <!-- Label was always "Créer + découper", but the splitter only
               runs when autoSplit is checked (default off). Dynamic label
               so the button matches what'll actually happen. -->
          <button type="submit" class="primary" disabled={phase === "creating" || !description.trim()}>
            {phase === "creating"
              ? t("create_task.button.submitting")
              : autoSplit
                ? t("create_task.button.submit_split")
                : t("create_task.button.submit_create")}
          </button>
        </footer>
      </form>
    {:else if phase === "clarify"}
      <div class="body">
        <p class="muted">{t("create_task.clarify.body")}</p>
        {#each clarificationPrompts as prompt (prompt.id)}
          <section class="clarification-card">
            <h3>{prompt.question}</h3>
            <div class="clarification-options">
              {#each prompt.options as option (option.value)}
                <button
                  type="button"
                  class:selected={clarificationAnswers[prompt.id] === option.value}
                  onclick={() => setClarificationAnswer(prompt.id, option.value)}
                >
                  {option.label}
                </button>
              {/each}
            </div>
            <textarea
              rows="2"
              value={clarificationAnswers[prompt.id] ?? ""}
              placeholder={t("create_task.clarify.free_placeholder")}
              oninput={(event) => setClarificationAnswer(prompt.id, (event.currentTarget as HTMLTextAreaElement).value)}
            ></textarea>
          </section>
        {/each}
        <footer>
          <button type="button" onclick={() => (phase = "input")}>{t("create_task.button.back")}</button>
          <button
            type="button"
            class="primary"
            disabled={!clarificationComplete}
            onclick={continueAfterClarification}
          >{t("create_task.button.continue")}</button>
        </footer>
      </div>
    {:else if phase === "splitting"}
      <div class="body centered">
        <div class="spinner" aria-hidden="true">⟳</div>
        <p>{t("create_task.splitting.body")}</p>
        <p class="muted">{t("create_task.splitting.help")}</p>
      </div>
    {:else if phase === "proposal"}
      <div class="body">
        <p class="rationale"><strong>{t("create_task.proposal.rationale")}</strong> ({proposalModel}) — {proposalRationale}</p>
        {#if proposalTasks.length === 0}
          <p class="muted">{t("create_task.proposal.empty")}</p>
        {:else}
          <ul class="proposed">
            {#each proposalTasks as task, i (i)}
              <li class="proposed-item">
                <div class="proposed-row">
                  <input
                    class="proposed-title"
                    type="text"
                    bind:value={task.title}
                    placeholder={t("create_task.field.title")}
                  />
                  <select bind:value={task.repo}>
                    {#each availableRepos as repo (repo)}
                      <option value={repo}>{repo}</option>
                    {/each}
                  </select>
                  <select bind:value={task.risk}>
                    <option value="low">low</option>
                    <option value="medium">medium</option>
                    <option value="high">high</option>
                  </select>
                  <button type="button" class="remove" onclick={() => removeProposalTask(i)} title={t("create_task.proposal.remove")}>✕</button>
                </div>
                {#if task.scopes.length > 0}
                  <div class="scopes">{task.scopes.join(" · ")}</div>
                {/if}
              </li>
            {/each}
          </ul>
        {/if}
        <footer>
          <button type="button" onclick={skipSplit}>{t("create_task.proposal.button.skip")}</button>
          <button
            type="button"
            class="primary"
            onclick={applyProposal}
            disabled={proposalTasks.length === 0}
          >
            {t("create_task.proposal.button.apply", { count: proposalTasks.length })}
          </button>
        </footer>
      </div>
    {:else if phase === "applying"}
      <div class="body centered">
        <div class="spinner" aria-hidden="true">⟳</div>
        <p>{t("create_task.applying.body")}</p>
      </div>
    {:else if phase === "applied"}
      <div class="body centered">
        <p class="success">{t("create_task.applied.success")}</p>
        {#if createdTask?.title}
          <p class="title-preview">
            <strong>{createdTask.title}</strong>
            {#if titleSource === "ai"}
              <span class="title-source ai">{t("create_task.title_source.ai", { model: titleModel ?? "AI" })}</span>
            {:else if titleSource === "fallback"}
              <span class="title-source fallback">{t("create_task.title_source.fallback")}</span>
            {/if}
          </p>
        {/if}
        {#if aiUnavailable}
          <p class="muted">{t("create_task.applied.ai_unavailable", { detail: aiUnavailableDetail })}</p>
        {/if}
        <footer>
          <button
            type="button"
            class="primary"
            onclick={closeDialog}
          >{t("create_task.applied.close")}</button>
        </footer>
      </div>
    {/if}
  </div>
</div>

<style>
  .execution {
    border: 1px solid var(--border-default);
    border-radius: 6px;
    padding: 8px 12px 6px;
    background: var(--bg-elevated);
    display: flex;
    flex-direction: column;
    gap: 6px;
  }
  .execution legend {
    padding: 0 4px;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--text-muted);
    font-weight: 600;
  }
  .toggle {
    display: flex; align-items: flex-start; gap: 8px;
    cursor: pointer;
  }
  .toggle input[type="checkbox"] {
    width: 14px; height: 14px;
    margin-top: 2px;
    accent-color: var(--accent);
    flex-shrink: 0;
  }
  .toggle-label {
    display: block; font-size: 13px; color: var(--text-primary);
  }
  .toggle-desc {
    display: block; font-size: 11px; color: var(--text-muted); margin-top: 1px;
  }
  .field-hint {
    display: block;
    margin-top: 3px;
    font-size: 11px;
    color: var(--text-muted);
  }
  .select-row {
    display: grid;
    grid-template-columns: 140px 200px 1fr;
    align-items: center;
    gap: 10px;
    margin-top: 8px;
    font-size: 13px;
  }
  .select-row select {
    padding: 4px 6px;
    border: 1px solid var(--border-field);
    border-radius: 4px;
    background: var(--bg-input);
    font: inherit;
  }
  .select-label { color: var(--text-primary); }
  .select-hint { font-size: 11px; color: var(--text-muted); font-style: italic; }
  .ai-tuning {
    display: grid;
    grid-template-columns: minmax(0, 1fr);
    gap: 8px;
    margin: 4px 0 8px 26px;
  }
  .number-row {
    display: flex;
    align-items: center;
    gap: 6px;
    font-size: 12px;
    color: var(--text-secondary);
  }
  .number-row input {
    width: 54px;
    padding: 3px 6px;
    border: 1px solid var(--border-field);
    border-radius: 4px;
    background: var(--bg-input);
    font: inherit;
    font-size: 12px;
  }
  .select-row.compact {
    grid-template-columns: 140px minmax(180px, 1fr);
    gap: 8px;
    margin-top: 0;
  }
  .select-row.compact .select-hint {
    grid-column: 2;
  }
  .prompt-row {
    display: grid;
    gap: 4px;
    font-size: 12px;
    color: var(--text-secondary);
  }
  .prompt-row textarea {
    width: 100%;
    min-height: 72px;
    resize: vertical;
    border: 1px solid var(--border-field);
    border-radius: 4px;
    background: var(--bg-input);
    color: var(--text-primary);
    font: inherit;
    font-size: 12px;
    line-height: 1.4;
    padding: 6px 8px;
  }
  .clarification-card {
    border: 1px solid var(--border-default);
    background: var(--bg-elevated);
    border-radius: 6px;
    padding: 10px;
    display: grid;
    gap: 8px;
  }
  .clarification-card h3 {
    margin: 0;
    font-size: 13px;
    color: var(--text-primary);
  }
  .clarification-options {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
  }
  .clarification-options button {
    border: 1px solid var(--border-field);
    background: var(--bg-surface);
    color: var(--text-secondary);
    border-radius: 4px;
    padding: 4px 8px;
    font: inherit;
    font-size: 12px;
    cursor: pointer;
  }
  .clarification-options button.selected {
    border-color: var(--accent);
    background: var(--accent-bg);
    color: var(--accent-text);
  }
  .clarification-card textarea {
    min-height: 48px;
    background: var(--bg-input);
    color: var(--text-primary);
  }
  /* Was a 3px accent border-left. DESIGN.md keeps the coloured side
     rail for exactly one thing — the priority rail on a card — so the
     emphasis moves onto the fill instead of a second rail. */
  .title-preview {
    margin: 8px auto;
    padding: 10px 14px;
    background: var(--accent-bg);
    border: 1px solid var(--accent);
    border-radius: 6px;
    text-align: left;
    max-width: 420px;
  }
  .title-preview strong { display: block; font-size: 14px; color: var(--text-primary); }
  .title-source {
    display: inline-block;
    margin-top: 4px;
    font-size: 11px;
    padding: 1px 6px;
    border-radius: 3px;
  }
  .title-source.ai { background: var(--accent-bg); color: var(--accent-text); }
  .title-source.fallback { background: var(--warning-bg); color: var(--warning); }
  .backdrop {
    position: fixed;
    inset: 0;
    background: var(--backdrop);
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 100;
  }
  .modal {
    background: var(--bg-surface);
    border-radius: 8px;
    box-shadow: var(--shadow-modal);
    max-width: 640px;
    width: 92%;
    display: flex;
    flex-direction: column;
    max-height: 85vh;
    max-height: 85dvh;
    overflow: hidden;
  }
  header {
    padding: 16px 20px;
    border-bottom: 1px solid var(--border-default);
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  h2 { margin: 0; font-size: 16px; }
  /* min-width/min-height rather than padding: WCAG 2.5.8's 24px floor
     without moving the header layout. */
  .close {
    background: transparent;
    border: none;
    font-size: 18px;
    cursor: pointer;
    color: var(--text-secondary);
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: var(--tap-size);
    min-height: var(--tap-size);
    border-radius: 4px;
  }
  .close:focus-visible {
    outline: 2px solid var(--accent);
    outline-offset: 2px;
  }
  .error { background: var(--warning-bg); color: var(--warning); padding: 8px 20px; font-size: 12px; }
  .body {
    padding: 16px 20px;
    display: flex;
    flex-direction: column;
    gap: 12px;
    overflow-y: auto;
  }
  .body.centered {
    align-items: center;
    text-align: center;
    padding: 32px 20px;
  }
  .spinner {
    font-size: 18px;
    color: var(--accent);
    animation: spin 1.2s linear infinite;
  }
  @keyframes spin { to { transform: rotate(360deg); } }
  .muted { color: var(--text-muted); font-size: 12px; }
  .success { color: var(--success); font-size: 16px; font-weight: 600; }
  label {
    display: flex;
    flex-direction: column;
    gap: 4px;
    font-size: 12px;
    color: var(--text-secondary);
  }
  input, select, textarea {
    padding: 6px 8px;
    border: 1px solid var(--border-field);
    border-radius: 4px;
    font-size: 13px;
    font-family: inherit;
  }
  /* A placeholder is text in the WCAG sense — it bottoms out at
     --text-muted like every other readable ink. */
  input::placeholder,
  textarea::placeholder { color: var(--text-muted); }
  textarea { resize: vertical; }
  .repos {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    align-items: center;
    font-size: 12px;
    color: var(--text-secondary);
  }
  .repos .label { margin-right: 4px; }
  .chip {
    flex-direction: row !important;
    align-items: center;
    gap: 4px;
    padding: 2px 6px;
    background: var(--bg-hover);
    border: 1px solid var(--border-strong);
    border-radius: 3px;
    cursor: pointer;
  }
  .rationale {
    background: var(--accent-bg);
    border-radius: 6px;
    padding: 10px 12px;
    font-size: 12px;
    color: var(--accent-text);
    margin: 0;
    line-height: 1.5;
  }
  .proposed {
    list-style: none;
    padding: 0;
    margin: 0;
    display: flex;
    flex-direction: column;
    gap: 8px;
  }
  .proposed-item {
    border: 1px solid var(--border-strong);
    border-radius: 6px;
    padding: 8px 10px;
    background: var(--bg-muted);
  }
  .proposed-row {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    align-items: center;
  }
  .proposed-title { flex: 1; min-width: 140px; }
  .scopes {
    margin-top: 4px;
    font-size: 11px;
    color: var(--text-muted);
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  }
  .remove {
    background: transparent;
    border: 1px solid var(--danger);
    color: var(--danger);
    border-radius: 3px;
    padding: 2px 8px;
    cursor: pointer;
    font-size: 11px;
  }
  .remove:hover { background: var(--danger-bg); }
  footer {
    margin-top: 8px;
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-end;
    gap: 8px;
  }
  button {
    background: var(--bg-hover);
    border: 1px solid var(--border-strong);
    border-radius: 4px;
    padding: 6px 12px;
    cursor: pointer;
    font-size: 13px;
    min-height: var(--tap-size);
  }
  button:focus-visible {
    outline: 2px solid var(--accent);
    outline-offset: 2px;
  }
  button.primary {
    background: var(--accent);
    color: var(--accent-on);
    border-color: var(--accent);
  }
  /* Neutral disabled fill pair — --text-subtle is never a background. */
  button.primary:disabled {
    background: var(--text-muted);
    border-color: var(--text-muted);
    color: var(--text-inverse);
    cursor: not-allowed;
  }

  /* 640 — src/lib/shell/breakpoints.ts (BP_NARROW). Below it the modal
     is ~330px wide: the three-track select rows can no longer hold
     140px + 200px side by side without clipping their hint. */
  @media (max-width: 640px) {
    .select-row,
    .select-row.compact {
      grid-template-columns: minmax(0, 1fr);
      gap: 4px;
    }
    .select-row.compact .select-hint {
      grid-column: 1;
    }
    .ai-tuning {
      margin-left: 0;
    }
  }
</style>
